### ISSUE TITLE
SKIP_MCP doesn't work

### ISSUE THREAD

**Issue by binarybana** [google-apis-rs/generated#1]
Small but annoying issue: I tried following the readme and no matter what I tried, `SKIP_MCP` wasn't taking:
```
SKIP_MCP=yes just SKIP_MCP=yes refresh-all
just clear-errors generator
Clearing all errors...
find gen -name 'generator-errors.log' -exec rm -v '{}' \;
just update-drivers
+ [[ no = \y\e\s ]]
+ '[' '!' -d ../generator ']'
...
$ just --version
just v0.4.4
```

Not sure what the problem was but don't have time to dig into it now.

**Comment by Byron** [comment]
Thanks a lot! The problem was that `just` called itself internally, without passing on the command-line arguments.

Trying to make `just` avoid work like `make` is a little more involved, unfortunately. On the other hand, `just` is not `make`, so no hard feelings :D.
